GET http://localhost:5000

###

GET http://localhost:5000/api/v1/timerset/d9a36958

###

POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
  "email": "atomrem@gmail.com",
  "password": "123456"
}