GET http://localhost:5000

###

POST http://localhost:5000/api/v1/timerset
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmYzVhYjcxODVlYWEzMTFkODFjM2E3ZSIsImlhdCI6MTYwOTM2NjQwNSwiZXhwIjoxNjA5NDUyODA1fQ._-pVheYroqbS8gorxvJ_gW5a2F_eIcO-jldLuCCRcdY
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmYzVhYjcxODVlYWEzMTFkODFjM2E3ZSIsImlhdCI6MTYwOTM2NDE4M30.As4GG4QbWftPXnJeNfr5xzA9fFPhNcSYYJfKt4OPDNY"
}

###

GET http://localhost:5000/api/v1/timerset/d9a36958

###

POST http://localhost:5000/api/v1/timerset/d9a36958/start/5fc0b554c6330151a659ce53
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmYzBiNTU0YzYzMzAxNTFhNjU5Y2U1MCIsImlhdCI6MTYwNjQ2NTM3MSwiZXhwIjoxNjA2NTUxNzcxfQ.SYhDYTohaxzpdjsIfdMRtDSgKmHzgiaEt9Nk_FdNvN0

###

POST http://localhost:5000/api/v1/timerset/d9a36958/stop/5fc0b554c6330151a659ce53
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmYzBiNTU0YzYzMzAxNTFhNjU5Y2U1MCIsImlhdCI6MTYwNjQ2NTM3MSwiZXhwIjoxNjA2NTUxNzcxfQ.SYhDYTohaxzpdjsIfdMRtDSgKmHzgiaEt9Nk_FdNvN0

###

POST http://localhost:5000/api/v1/timerset/reset/d9a36958
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmYzBiNTU0YzYzMzAxNTFhNjU5Y2U1MCIsImlhdCI6MTYwNjQ2NTM3MSwiZXhwIjoxNjA2NTUxNzcxfQ.SYhDYTohaxzpdjsIfdMRtDSgKmHzgiaEt9Nk_FdNvN0

###

POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
  "email": "atomrem@gmail.com",
  "password": "123456"
}

###
GET http://localhost:5000/api/v1/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmYzBiNTU0YzYzMzAxNTFhNjU5Y2U1MCIsImlhdCI6MTYwNjQ2NTM3MSwiZXhwIjoxNjA2NTUxNzcxfQ.SYhDYTohaxzpdjsIfdMRtDSgKmHzgiaEt9Nk_FdNvN0
