export const GET_ALLTIMERSET_REQUEST = "GET_ALLTIMERSET_REQUEST";
export const GET_ALLTIMERSET_SUCCESS = "GET_ALLTIMERSET_SUCCESS";
export const GET_ALLTIMERSET_FAIL = "GET_ALLTIMERSET_FAIL";

export const GET_TIMERSET_REQUEST = "GET_TIMERSET_REQUEST";
export const GET_TIMERSET_SUCCESS = "GET_TIMERSET_SUCCESS";
export const GET_TIMERSET_FAIL = "GET_TIMERSET_FAIL";
export const CLEAR_TIMERSET = "CLEAR_TIMERSET";

export const ADD_TIMERSET_MAIN_REQUEST = "ADD_TIMERSET_MAIN_REQUEST";
export const ADD_TIMERSET_MAIN_SUCCESS = "ADD_TIMERSET_MAIN_SUCCESS";
export const ADD_TIMERSET_MAIN_FAIL = "ADD_TIMERSET_MAIN_FAIL";
export const ADD_TIMERSET_MAIN_RESET = "ADD_TIMERSET_MAIN_RESET";

export const UPDATE_TIMERSET_REQUEST = "UPDATE_TIMERSET_REQUEST";
export const UPDATE_TIMERSET_SUCCESS = "UPDATE_TIMERSET_SUCCESS";
export const UPDATE_TIMERSET_FAIL = "UPDATE_TIMERSET_FAIL";
export const UPDATE_TIMERSET_RESET = "UPDATE_TIMERSET_RESET";

export const DELETE_TIMERSET_REQUEST = "DELETE_TIMERSET_REQUEST";
export const DELETE_TIMERSET_SUCCESS = "DELETE_TIMERSET_SUCCESS";
export const DELETE_TIMERSET_FAIL = "DELETE_TIMERSET_FAIL";
export const DELETE_TIMERSET_RESET = "DELETE_TIMERSET_RESET";

export const SHOW_ADD_TIMERSET_MAIN = "SHOW_ADD_TIMERSET_MAIN";
export const HIDE_ADD_TIMERSET_MAIN = "HIDE_ADD_TIMERSET_MAIN";

export const SHOW_UPDATE_TIMERSET_MAIN = "SHOW_UPDATE_TIMERSET_MAIN";
export const HIDE_UPDATE_TIMERSET_MAIN = "HIDE_UPDATE_TIMERSET_MAIN";

export const SHOW_DELETE_TIMERSET_MAIN = "SHOW_DELETE_TIMERSET_MAIN";
export const HIDE_DELETE_TIMERSET_MAIN = "HIDE_DELETE_TIMERSET_MAIN";

export const SAVE_TIMERSET_REQUEST = "SAVE_TIMERSET_REQUEST";
export const SAVE_TIMERSET_SUCCESS = "SAVE_TIMERSET_SUCCESS";
export const SAVE_TIMERSET_FAIL = "SAVE_TIMERSET_FAIL";
export const SAVE_TIMERSET_RESET = "SAVE_TIMERSET_RESET";

export const START_TIMER_REQUEST = "START_TIMER_REQUEST";
export const START_TIMER_SUCCESS = "START_TIMER_SUCCESS";
export const START_TIMER_FAIL = "START_TIMER_FAIL";

export const STOP_TIMER_REQUEST = "STOP_TIMER_REQUEST";
export const STOP_TIMER_SUCCESS = "STOP_TIMER_SUCCESS";
export const STOP_TIMER_FAIL = "STOP_TIMER_FAIL";

export const ACTIVATE_TIMER = "ACTIVATE_TIMER";
export const DEACTIVATE_TIMER = "DEACTIVATE_TIMER";

export const RESET_TIMERSET_REQUEST = "RESET_TIMERSET_REQUEST";
export const RESET_TIMERSET_SUCCESS = "RESET_TIMERSET_SUCCESS";
export const RESET_TIMERSET_FAIL = "RESET_TIMERSET_FAIL";
