export const GET_ALLTIMERSET_REQUEST = "GET_ALLTIMERSET_REQUEST";
export const GET_ALLTIMERSET_SUCCESS = "GET_ALLTIMERSET_SUCCESS";
export const GET_ALLTIMERSET_FAIL = "GET_ALLTIMERSET_FAIL";

export const GET_TIMERSET_REQUEST = "GET_TIMERSET_REQUEST";
export const GET_TIMERSET_SUCCESS = "GET_TIMERSET_SUCCESS";
export const GET_TIMERSET_FAIL = "GET_TIMERSET_FAIL";
export const CLEAR_TIMERSET = "CLEAR_TIMERSET";

export const SAVE_TIMERSET_REQUEST = "SAVE_TIMERSET_REQUEST";
export const SAVE_TIMERSET_SUCCESS = "SAVE_TIMERSET_SUCCESS";
export const SAVE_TIMERSET_FAIL = "SAVE_TIMERSET_FAIL";
export const SAVE_TIMERSET_RESET = "SAVE_TIMERSET_RESET";

export const UPDATE_TIMERSET_REQUEST = "UPDATE_TIMERSET_REQUEST";
export const UPDATE_TIMERSET_SUCCESS = "UPDATE_TIMERSET_SUCCESS";
export const UPDATE_TIMERSET_FAIL = "UPDATE_TIMERSET_FAIL";
export const UPDATE_TIMERSET_RESET = "UPDATE_TIMERSET_RESET";

export const DELETE_TIMERSET_REQUEST = "DELETE_TIMERSET_REQUEST";
export const DELETE_TIMERSET_SUCCESS = "DELETE_TIMERSET_SUCCESS";
export const DELETE_TIMERSET_FAIL = "DELETE_TIMERSET_FAIL";
export const DELETE_TIMERSET_RESET = "DELETE_TIMERSET_RESET";

export const SHOW_ADD_TIMERSET = "SHOW_ADD_TIMERSET";
export const HIDE_ADD_TIMERSET = "HIDE_ADD_TIMERSET";

export const SHOW_UPDATE_TIMERSET = "SHOW_UPDATE_TIMERSET";
export const HIDE_UPDATE_TIMERSET = "HIDE_UPDATE_TIMERSET";

export const SHOW_DELETE_TIMERSET = "SHOW_DELETE_TIMERSET";
export const HIDE_DELETE_TIMERSET = "HIDE_DELETE_TIMERSET";

export const SAVE_TIMER_REQUEST = "SAVE_TIMER_REQUEST";
export const SAVE_TIMER_SUCCESS = "SAVE_TIMER_SUCCESS";
export const SAVE_TIMER_FAIL = "SAVE_TIMER_FAIL";
export const SAVE_TIMER_RESET = "SAVE_TIMER_RESET";

export const UPDATE_TIMER_REQUEST = "UPDATE_TIMER_REQUEST";
export const UPDATE_TIMER_SUCCESS = "UPDATE_TIMER_SUCCESS";
export const UPDATE_TIMER_FAIL = "UPDATE_TIMER_FAIL";
export const UPDATE_TIMER_RESET = "UPDATE_TIMER_RESET";

export const DELETE_TIMER_REQUEST = "DELETE_TIMER_REQUEST";
export const DELETE_TIMER_SUCCESS = "DELETE_TIMER_SUCCESS";
export const DELETE_TIMER_FAIL = "DELETE_TIMER_FAIL";
export const DELETE_TIMER_RESET = "DELETE_TIMER_RESET";

export const SHOW_ADD_TIMER = "SHOW_ADD_TIMER";
export const HIDE_ADD_TIMER = "HIDE_ADD_TIMER";

export const SHOW_UPDATE_TIMER = "SHOW_UPDATE_TIMER";
export const HIDE_UPDATE_TIMER = "HIDE_UPDATE_TIMER";

export const SHOW_DELETE_TIMER = "SHOW_DELETE_TIMER";
export const HIDE_DELETE_TIMER = "HIDE_DELETE_TIMER";

export const START_TIMER_REQUEST = "START_TIMER_REQUEST";
export const START_TIMER_SUCCESS = "START_TIMER_SUCCESS";
export const START_TIMER_FAIL = "START_TIMER_FAIL";

export const STOP_TIMER_REQUEST = "STOP_TIMER_REQUEST";
export const STOP_TIMER_SUCCESS = "STOP_TIMER_SUCCESS";
export const STOP_TIMER_FAIL = "STOP_TIMER_FAIL";

export const ACTIVATE_TIMER = "ACTIVATE_TIMER";
export const DEACTIVATE_TIMER = "DEACTIVATE_TIMER";

export const RESET_TIMERSET_REQUEST = "RESET_TIMERSET_REQUEST";
export const RESET_TIMERSET_SUCCESS = "RESET_TIMERSET_SUCCESS";
export const RESET_TIMERSET_FAIL = "RESET_TIMERSET_FAIL";
