export const GET_TIMERSET_REQUEST = "GET_TIMERSET_REQUEST";
export const GET_TIMERSET_SUCCESS = "GET_TIMERSET_SUCCESS";
export const GET_TIMERSET_FAIL = "GET_TIMERSET_FAIL";

export const START_TIMER_REQUEST = "START_TIMER_REQUEST";
export const START_TIMER_SUCCESS = "START_TIMER_SUCCESS";
export const START_TIMER_FAIL = "START_TIMER_FAIL";

export const STOP_TIMER_REQUEST = "STOP_TIMER_REQUEST";
export const STOP_TIMER_SUCCESS = "STOP_TIMER_SUCCESS";
export const STOP_TIMER_FAIL = "STOP_TIMER_FAIL";

export const RESET_TIMERSET_REQUEST = "RESET_TIMERSET_REQUEST";
export const RESET_TIMERSET_SUCCESS = "RESET_TIMERSET_SUCCESS";
export const RESET_TIMERSET_FAIL = "RESET_TIMERSET_FAIL";
